### PR TITLE
Update dependencies for technical currency

### PR DESCRIPTION
**Pull request by t1m0thyj**
This PR resolves several vulnerabilities reported in transitive deps of `wdio-vscode-service` when I run `npm audit` in my project.

Replaced `download` package which has several vulnerabilities and has been unmaintained for a few years with a fork `@xhmikosr/downloader` that is actively maintained but unfortunately doesn't define TS types. This fork is reputable and used by other projects - see https://github.com/saucelabs/node-saucelabs/pull/195 and https://github.com/netlify/gh-release-fetch/issues/50

There is one vulnerability left in a prod dep: `webdriverio@8.40.5 -> puppeteer-core@21.11.0 -> ws@8.16.0`. This will be resolved by upgrading to webdriverio@9 in #130.

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
Awesome, LGTM 👍

**Comment by t1m0thyj** [comment]
@christian-bromann Thanks for merging so quickly! I just realized that `@xhmikosr/downloader@15` requires Node 18. Since `wdio-vscode-service` supports Node 16 I should have used `@xhmikosr/downloader@14` for max compatibility. Sorry for this oversight, let me know if I should open a follow-up PR.

**Comment by christian-bromann** [comment]
> Sorry for this oversight, let me know if I should open a follow-up PR.

No worries, mind raising a PR that updates the required Node version?

**Comment by XhmikosR** [comment]
Someone should update to the latest version, it fixes a couple more vulnerabilities and reduces deps further:

* https://npmgraph.js.org/?q=@xhmikosr/downloader@15.2.0
* https://npmgraph.js.org/?q=@xhmikosr/downloader

**Pull request merged**
