### PR TITLE
Contain side-effects from tests in C/I

### PR DESCRIPTION
**Pull request by sourishkrout**
Follow up to https://github.com/webdriverio-community/wdio-vscode-service/pull/98.

- Break out specs into separate files
- Make them pass again

### CODE REVIEW

**Comment by sourishkrout** [comment]
Test passed for various vscode versions on a Linux box. Hopefully 🤞 this will make them pass in GH actions, @christian-bromann.

**Comment by christian-bromann** [comment]
Thanks for the patch 👌

**Comment by christian-bromann** [comment]
@sourishkrout shouldn't we remove the tests from the `basic.e2e.ts` since they have been moved out into separate files?

**Comment by sourishkrout** [comment]
> @sourishkrout shouldn't we remove the tests from the `basic.e2e.ts` since they have been moved out into separate files?

I believe the whole file was removed. If not then I must have done something wrong during commit. Checking....

Also... Windows 🤦.

**Comment by sourishkrout** [comment]
Looks like this is right:

image

**Comment by christian-bromann** [comment]
> Looks like this is right:

Yes, thanks for confirming. The GitHub UI tricked me here.

**Comment by sourishkrout** [comment]
Just pushed a wdio config change to turn on retries for occasional flakes @christian-bromann.

**Comment by sourishkrout** [comment]
Got one of the culprits to pass consistently locally. Let's see if we can get a clean build, please, @christian-bromann.

**Comment by sourishkrout** [comment]
Chromedriver/Electron didn't even come up in the last run. Don't think that's related to the new commits. Crashed prematurely.

**Comment by sourishkrout** [comment]
🤦 whackamole continues

**Comment by sourishkrout** [comment]
🤞 hopefully this will fix it @christian-bromann

**Review by christian-bromann — APPROVED** [review]
Awesome, thanks a lot!

**Pull request merged**
