### PR TITLE
feat: set http proxy from env

### PR DESCRIPTION
**Pull request by openscript**
This is related with #86.

Undici doesn't support http proxies out of the box, but there is a ProxyAgent built in: https://undici.nodejs.org/#/docs/api/ProxyAgent

### CODE REVIEW

**Comment by openscript** [comment]
Hmm.. I think we need to proxy `download` too.

**Comment by openscript** [comment]
`@vscode/test-electron` reads proxy environment variables: https://github.com/microsoft/vscode-test/blob/c4b489f6052f4070839165bb88fcd11263f0460b/lib/util.ts#L60

**Comment by christian-bromann** [comment]
This is awesome, do you think we can add a sentence or two in the `README.md` to document this behavior?

**Comment by openscript** [comment]
> This is awesome, do you think we can add a sentence or two in the `README.md` to document this behavior?

Absolutely :smile: 

Is that failing test because of me?

**Comment by christian-bromann** [comment]
Probably not, I will have to check.

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Pull request merged**
